team: Georgia
starters:
  OL:
  - name: Earnest Greene III
    position_tag: LT
    jersey: '71'
    class_year: SR
    snaps_multi_year: 1093
    recruit_rating: 97
    recruit_stars: 4
  - name: Dontrell Glover
    position_tag: LG
    jersey: '63'
    class_year: SO
    snaps_multi_year: 818
    recruit_rating: 89
    recruit_stars: 3
  - name: Drew Bobo
    position_tag: C
    jersey: '74'
    class_year: SR
    snaps_multi_year: 998
    recruit_rating: 86
    recruit_stars: 3
  - name: Zykie Helton
    position_tag: RG
    jersey: '55'
    class_year: FR
    snaps_multi_year: 73
    recruit_rating: 90
    recruit_stars: 4
  - name: Juan Gaston
    position_tag: RT
    jersey: '73'
    class_year: SO
    snaps_multi_year: 542
    recruit_rating: 98
    recruit_stars: 5
  DL:
  - name: Gabe Harris Jr.
    position_tag: DE
    recruit_rating: 95
    recruit_stars: 4
  - name: Jordan Hall
    position_tag: NT
    jersey: '44'
    class_year: SR
    snaps_multi_year: 222
    recruit_rating: 99
    recruit_stars: 5
  - name: Elijah Griffin
    position_tag: DT
    jersey: '90'
    class_year: SO
    snaps_multi_year: 395
    recruit_rating: 100
    recruit_stars: 5
updated_by_human_at: '2026-09-16'
roster_source: ourlads.com (depth chart) + puntandrally.com (jersey/class/snaps enrichment),
  via run_week.py
offense_scheme: Pro Spread
defense_scheme: 3-4
